apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xbuckets.infrastructure.example.org
  labels:
    provider: gcp
spec:
  compositeTypeRef:
    apiVersion: infrastructure.example.org/v1alpha1
    kind: XBucket
  resources:
    - base:
        apiVersion: storage.gcp.upbound.io/v1beta1
        kind: Bucket
        spec:
          forProvider:
            location: US
            storageClass: MULTI_REGIONAL
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.annotations[crossplane.io/external-name]