apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnetworks.infrastructure.example.org
  labels:
    provider: aws
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: infrastructure.example.org/v1alpha1
    kind: XNetwork
  patchSets:
  - name: network-id
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.id
      toFieldPath: metadata.labels[networks.infrastructure.example.org/network-id]
  resources:
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: NetworkInterface
        spec:
          forProvider:
            region: us-west-1 # patched
            subnetIdSelector:
              matchControllerRef: true
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
        - fromFieldPath: spec.location
          toFieldPath: spec.forProvider.region
          transforms:
            - type: map
              map:
                'East US': 'us-east-1'
                'West US': 'us-west-1'
        - fromFieldPath: spec.id
          toFieldPath: metadata.labels[networks.infrastructure.example.org/nwinterface-id]
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        spec:
          forProvider:
            availabilityZone: us-west-1c # patched
            cidrBlock: 10.255.255.0/28
            region: us-west-1 # patched
            vpcIdSelector:
              matchControllerRef: true
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.labels[networks.infrastructure.example.org/subnet-id]
        - fromFieldPath: spec.location
          toFieldPath: spec.forProvider.region
          transforms:
            - type: map
              map:
                'East US': 'us-east-1'
                'West US': 'us-west-1'
        - fromFieldPath: spec.location
          toFieldPath: spec.forProvider.availabilityZone
          transforms:
            - type: map
              map:
                'East US': 'us-east-1c'
                'West US': 'us-west-1c'
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: VPC
        spec:
          forProvider:
            cidrBlock: 10.255.255.0/28
            region: us-east-1 # patched
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.labels[networks.infrastructure.example.org/vpc-id]
        - fromFieldPath: spec.location
          toFieldPath: spec.forProvider.region
          transforms:
            - type: map
              map:
                'East US': 'us-east-1'
                'West US': 'us-west-1'