apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: aws.xfunctions.infrastructure.example.org
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: infrastructure.example.org/v1alpha1
    kind: XFunction
  resources:
    - base:
        apiVersion: lambda.aws.upbound.io/v1beta1
        kind: Function
        spec:
          forProvider:
            handler: index.py
            region: us-east-1
            roleRef:
              name: sample-role
            runtime: python3.9
            s3Bucket: upbound-provider-test-data
            s3Key: hello-python.zip
      patches:
        - fromFieldPath: spec.parameters.location
          toFieldPath: spec.forProvider.location
          transforms:
            - type: map
              map:
                'East US': 'us-east-1'
                'West US': 'us-west-1'
        - fromFieldPath: spec.parameters.image
          toFieldPath: spec.forProvider.template[0].template[0].containers[0].image