apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcompositeamplifys.infrastructure.example.org
spec:
  group: infrastructure.example.org
  names:
    kind: XCompositeAmplify
    plural: xcompositeamplifys
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                repository:
                  type: string
                  description: "The repository where the app source code is hosted"
            status:
              type: object
              properties:
                domain:
                  type: string
                  description: "The domain for the frontend"
                branchName:
                  type: string
                  description: "The branch in the source repo being deployed"